rmf.repos

This PR switches the `rmf.repos` file to use the new repositories created by splitting up `osrf/rmf_core`.

Switch to split repositories for rmf_core

---

rmf.repos

Adds two new repositories, replacing `osrf/rmf_schedule_visualizer`:
1. `open-rmf/rmf_visualization`
2. `open-rmf/rmf_visualization_msgs`

Add new visualisation repositories

---

rmf.repos

This PR accounts for the recent split and reorganisation and move of the traffic editor repository.

Account for traffic editor repository reorganisation

---

rmf.repos

Currently the `rmf_traffic_editor` repo is in its own subdirectory when running `vcs import` on the `rmf.repos` file. This PR aligns it next to the other `rmf` repositories.
Also reflects the change in default branch name.
Signed-off-by: Morgan Quigley <morgan@osrfoundation.org>

Align traffic editor repo with others

---

README.md

These links used to be provided in the `rmf_core` repo, but I think they belong here now.

Add links to pertinent documentation pages

---

rmf.repos

Remove `ros_ign` and use the binary package instead, depends on [rmf_demos #60](https://github.com/open-rmf/rmf_demos/pull/60) which should be merged first.
Since `ros_ign` related packages are now available as binaries, we can avoid building them from source, saving some time and effort when updating distributions, as well as building time and size of the RMF workspace.

Remove ros_ign source repo

---

rmf.repos

We currently have the rmf_cmake_uncrustify package that is used for style checking with colcon test. The original reason for having this package and not using ament_cmake_uncrustify was that the latter did not support custom uncrustify configuration files. But this feature was [merged upstream](https://github.com/ament/ament_lint/pull/200) quite a while ago and has been part of `foxy` and `galactic` releases. Hence, switching back to `ament_cmake_uncrustify` for ease of maintenance and distribution.

Remove rmf_cmake_uncrustify

---

README.md

In the installation instructions, currently we suggest to use the `-r` flag during `rosdep install`, which tells `rosdep` to ignore errors. Unfortunately due to the amount of console output produced, it's basically impossible to note things like missing rosdep keys or other errors. This PR just removes the `-r` flag from the installation instructions, which will cause `rosdep` to halt when it sees an error, so that it's easier to track it down during dependency-installation, rather than at compilation time or run time.
Signed-off-by: Morgan Quigley <morgan@osrfoundation.org>

install instructions: don't pass rosdep the ignore-errors flag

---

README.md

Signed-off-by: Aaron Chong <aaronchongth@gmail.com>
Added note to mention that binary installations should be removed before source builds to prevent conflicts and compilation errors with older headers installed.

Adding note regarding uninstalling binaries before source build

---

Dockerfile
README.md

This PR updates the build instructions to support the demo fleet adapter integration by installing `fastapi` and `uvicorn` according to open-rmf/rmf_demos#109

add demo fleet adapter build instructions

---

.github/workflows/nightly.yaml
Dockerfile
README.md
rmf.repos

This PR 
1. Merges in latest `main` into `galactic`
2. Updates the `rmf.repos` file to checkout `galactic-devel` branches of the Open-RMF repos which has recently been created.
Moving forward `main` will be supported on `humble`. See https://github.com/open-rmf/rmf/pull/165
We can add instructions to that PR to inform users to use the `galactic` version of the `rmf.repos` file if the would like to build `Open-RMF` from source + `galactic`

Update galactic branch

---

README.md

Signed-off-by: Aaron Chong <aaronchongth@gmail.com>
Fixes mistakes in build instructions mentioned in https://github.com/open-rmf/rmf/discussions/224#discussioncomment-3655587.

Fixing clang CC variable, mixin without apostrophes

---

README.md

https://github.com/open-rmf/rmf/issues/249 
This dependency seems not to be possible to install via rosdep - I searched here: https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
So it can't be added to package.xml of rmf_api_msgs. It has to be added probably to the installation tutorial.

Fix missing dependency of rmf_api_msgs

---

README.md

As rmf-demos packages are currently not available, README.md has been updated accordingly.

RMF demos readme minor fix

---

README.md

Building with `clang` and `lld` without installing `libstdc++-12-dev` leads to linker errors when trying to compile trivial C++ code on ubuntu 22.04. This PR updates the instructions to have users install the correct version of `libstdc++-12-dev`. Thanks @Yadunund for the suggestion.
Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>

Updates Clang and LLD install instructions

---

README.md

Updating the main installation instructions for Open-RMF to prioritize building from source. Also adding the missing 22.09 release link.

Update main install docs

---

.github/workflows/mirror-main-to-rolling.yaml

There is a `rolling` distro branch in this repo but since we distribute packages to `rolling` from `main` of all repos, we will simply have the `rolling` branch here mirror the `main` branch. This PR adds a github action that will ensure rolling is just a mirror of main.

Add workflow to mirror main to rolling

---

README.md

Fixes https://github.com/open-rmf/rmf/issues/372.
* remove `datamodel_code_generator` from installation step as it is not released by binaries, and only emits a warning even when building `rmf_api_msgs` from source, not crashing the build, as per https://github.com/open-rmf/rmf/issues/249
* `datamodel_code_generator` will only be used if a user is trying to create their own `api-server` via the schemas from `rmf_api_msgs`, otherwise it is not used at all
* any mentions of `datamodel_code_generator` will only be in `rmf_api_msgs`
Using `podman`,
```bash
podman run -it docker.io/library/ros:humble-ros-base-jammy
mkdir -p ~/ws/src
cd ~/ws/src
git clone https://github.com/open-rmf/rmf_api_msgs
cd ~/ws
rosdep install --from-paths src --ignore-src --rosdistro humble -y
source …
```

Removing datamodel_code_generator from main installation step

---

rmf.repos

Quality of life improvement to make version bump diffs easier to manage as `vcs export --exact-with-tags` will export the repos in a alphabetical order. This would avoid doing this for every `distro` branch we create when a new ROS 2 version is released.

Alphabetize entries in repos file

---

README.md

I know we ask the user to run `rosdep update` when they install `ros-dev-tools` for the first time. However, it probably is a good idea to `rosdep update` before running `rosdep install`.

Add `rosdep update`  before `rosdep install`

---

.github/workflows/nightly.yaml

The nightly build has been failing for a while because we've been stuck on a deprecated version of `actions/upload-artifact`. This PR brings it to the same version that we're using in the reusable workflow template.

Use a newer version of upload-artifact
